# Generated by Django 5.1.7 on 2025-04-25 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('momo', 'MoMo'), ('vnpay', 'VNPAY'), ('bank', 'Bank Transfer')], max_length=10)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('member_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='packages.memberpackage')),
            ],
        ),
    ]
